# Variables
# ---------

ZIG := zig
BC := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
# option test filter make test F="server"
F=

# OS and ARCH
kernel = $(shell uname -ms)
ifeq ($(kernel), Darwin arm64)
	OS := macos
	ARCH := aarch64
else ifeq ($(kernel), Darwin x86_64)
	OS := macos
	ARCH := x86_64
else ifeq ($(kernel), Linux aarch64)
	OS := linux
	ARCH := aarch64
else ifeq ($(kernel), Linux arm64)
	OS := linux
	ARCH := aarch64
else ifeq ($(kernel), Linux x86_64)
	OS := linux
	ARCH := x86_64
else
	$(error "Unhandled kernel: $(kernel)")
endif


# Infos
# -----
.PHONY: help

## Display this help screen
help:
	@printf "\e[36m%-35s %s\e[0m\n" "Command" "Usage"
	@sed -n -e '/^## /{'\
		-e 's/## //g;'\
		-e 'h;'\
		-e 'n;'\
		-e 's/:.*//g;'\
		-e 'G;'\
		-e 's/\n/ /g;'\
		-e 'p;}' Makefile | awk '{printf "\033[33m%-35s\033[0m%s\n", $$1, substr($$0,length($$1)+1)}'


# $(ZIG) commands
# ------------
.PHONY: build build-dev run run-release shell test bench wpt data end2end

## Build in release-safe mode
build:
	@printf "\e[36mBuilding (release safe)...\e[0m\n"
	$(ZIG) build -Doptimize=ReleaseSafe -Dgit_commit=$$(git rev-parse --short HEAD) || (printf "\e[33mBuild ERROR\e[0m\n"; exit 1;)
	@printf "\e[33mBuild OK\e[0m\n"

## Build in debug mode
build-dev:
	@printf "\e[36mBuilding (debug)...\e[0m\n"
	@$(ZIG) build -Dgit_commit=$$(git rev-parse --short HEAD) || (printf "\e[33mBuild ERROR\e[0m\n"; exit 1;)
	@printf "\e[33mBuild OK\e[0m\n"

## Run the server in release mode
run: build
	@printf "\e[36mRunning...\e[0m\n"
	@./zig-out/bin/lightpanda || (printf "\e[33mRun ERROR\e[0m\n"; exit 1;)

## Run the server in debug mode
run-debug: build-dev
	@printf "\e[36mRunning...\e[0m\n"
	@./zig-out/bin/lightpanda || (printf "\e[33mRun ERROR\e[0m\n"; exit 1;)

## Run a JS shell in debug mode
shell:
	@printf "\e[36mBuilding shell...\e[0m\n"
	@$(ZIG) build shell || (printf "\e[33mBuild ERROR\e[0m\n"; exit 1;)

## Run WPT tests
wpt:
	@printf "\e[36mBuilding wpt...\e[0m\n"
	@$(ZIG) build wpt -- $(filter-out $@,$(MAKECMDGOALS)) || (printf "\e[33mBuild ERROR\e[0m\n"; exit 1;)

wpt-summary:
	@printf "\e[36mBuilding wpt...\e[0m\n"
	@$(ZIG) build wpt -- --summary $(filter-out $@,$(MAKECMDGOALS)) || (printf "\e[33mBuild ERROR\e[0m\n"; exit 1;)

## Test - `grep` is used to filter out the huge compile command on build
ifeq ($(OS), macos)
test:
	@script -q /dev/null sh -c 'TEST_FILTER="${F}" $(ZIG) build test -freference-trace --summary all' 2>&1 \
		| grep --line-buffered -v "^/.*zig test -freference-trace"
else
test:
	@script -qec 'TEST_FILTER="${F}" $(ZIG) build test -freference-trace --summary all' /dev/null 2>&1 \
		| grep --line-buffered -v "^/.*zig test -freference-trace"
endif

## Run demo/runner end to end tests
end2end:
	@test -d ../demo
	cd ../demo && go run runner/main.go

# Install and build required dependencies commands
# ------------
.PHONY: install-submodule
.PHONY: install-libiconv
.PHONY: _install-netsurf install-netsurf clean-netsurf test-netsurf install-netsurf-dev
.PHONY: install-mimalloc install-mimalloc-dev clean-mimalloc
.PHONY: install-dev install

## Install and build dependencies for release
install: install-submodule install-libiconv install-netsurf install-mimalloc

## Install and build dependencies for dev
install-dev: install-submodule install-libiconv install-netsurf-dev install-mimalloc-dev

install-netsurf-dev: _install-netsurf
install-netsurf-dev: OPTCFLAGS := -O0 -g -DNDEBUG

install-netsurf: _install-netsurf
install-netsurf: OPTCFLAGS := -DNDEBUG

BC_NS := $(BC)vendor/netsurf/out/$(OS)-$(ARCH)
ICONV := $(BC)vendor/libiconv/out/$(OS)-$(ARCH)
# TODO: add Linux iconv path (I guess it depends on the distro)
# TODO: this way of linking libiconv is not ideal. We should have a more generic way
# and stick to a specif version. Maybe build from source. Anyway not now.
_install-netsurf: clean-netsurf
	@printf "\e[36mInstalling NetSurf...\e[0m\n" && \
	ls $(ICONV)/lib/libiconv.a 1> /dev/null || (printf "\e[33mERROR: you need to execute 'make install-libiconv'\e[0m\n"; exit 1;) && \
	mkdir -p $(BC_NS) && \
	cp -R vendor/netsurf/share $(BC_NS) && \
	export PREFIX=$(BC_NS) && \
	export OPTLDFLAGS="-L$(ICONV)/lib" && \
	export OPTCFLAGS="$(OPTCFLAGS) -I$(ICONV)/include" && \
	printf "\e[33mInstalling libwapcaplet...\e[0m\n" && \
	cd vendor/netsurf/libwapcaplet && \
	BUILDDIR=$(BC_NS)/build/libwapcaplet make install && \
	cd ../libparserutils && \
	printf "\e[33mInstalling libparserutils...\e[0m\n" && \
	BUILDDIR=$(BC_NS)/build/libparserutils make install && \
	cd ../libhubbub && \
	printf "\e[33mInstalling libhubbub...\e[0m\n" && \
	BUILDDIR=$(BC_NS)/build/libhubbub make install && \
	rm src/treebuilder/autogenerated-element-type.c && \
	cd ../libdom && \
	printf "\e[33mInstalling libdom...\e[0m\n" && \
	BUILDDIR=$(BC_NS)/build/libdom make install && \
	printf "\e[33mRunning libdom example...\e[0m\n" && \
	cd examples && \
	$(ZIG) cc \
	-I$(ICONV)/include \
	-I$(BC_NS)/include \
	-L$(ICONV)/lib \
	-L$(BC_NS)/lib \
	-liconv \
	-ldom \
	-lhubbub \
	-lparserutils \
	-lwapcaplet \
	-o a.out \
	dom-structure-dump.c \
	$(ICONV)/lib/libiconv.a && \
	./a.out > /dev/null && \
	rm a.out && \
	printf "\e[36mDone NetSurf $(OS)\e[0m\n"

clean-netsurf:
	@printf "\e[36mCleaning NetSurf build...\e[0m\n" && \
	rm -Rf $(BC_NS)

test-netsurf:
	@printf "\e[36mTesting NetSurf...\e[0m\n" && \
	export PREFIX=$(BC_NS) && \
	export LDFLAGS="-L$(ICONV)/lib -L$(BC_NS)/lib" && \
	export CFLAGS="-I$(ICONV)/include -I$(BC_NS)/include" && \
	cd vendor/netsurf/libdom && \
	BUILDDIR=$(BC_NS)/build/libdom make test

download-libiconv:
ifeq ("$(wildcard vendor/libiconv/libiconv-1.17)","")
	@mkdir -p vendor/libiconv
	@cd vendor/libiconv && \
	curl -L https://github.com/lightpanda-io/libiconv/releases/download/1.17/libiconv-1.17.tar.gz | tar -xvzf -
endif

build-libiconv: clean-libiconv
	@cd vendor/libiconv/libiconv-1.17 && \
	./configure --prefix=$(ICONV) --enable-static && \
	make && make install

install-libiconv: download-libiconv build-libiconv

clean-libiconv:
ifneq ("$(wildcard vendor/libiconv/libiconv-1.17/Makefile)","")
	@cd vendor/libiconv/libiconv-1.17 && \
	make clean
endif

data:
	cd src/data && go run public_suffix_list_gen.go > public_suffix_list.zig

.PHONY: _build_mimalloc

MIMALLOC := $(BC)vendor/mimalloc/out/$(OS)-$(ARCH)
_build_mimalloc: clean-mimalloc
	@mkdir -p $(MIMALLOC)/build && \
	cd $(MIMALLOC)/build && \
	cmake -DMI_BUILD_SHARED=OFF -DMI_BUILD_OBJECT=OFF -DMI_BUILD_TESTS=OFF -DMI_OVERRIDE=OFF $(OPTS) ../../.. && \
	make && \
	mkdir -p $(MIMALLOC)/lib

install-mimalloc-dev: _build_mimalloc
install-mimalloc-dev: OPTS=-DCMAKE_BUILD_TYPE=Debug
install-mimalloc-dev:
	@cd $(MIMALLOC) && \
	mv build/libmimalloc-debug.a lib/libmimalloc.a

install-mimalloc: _build_mimalloc
install-mimalloc:
	@cd $(MIMALLOC) && \
	mv build/libmimalloc.a lib/libmimalloc.a

clean-mimalloc:
	@rm -Rf $(MIMALLOC)/build

## Init and update git submodule
install-submodule:
	@git submodule init && \
	git submodule update

# curl-impersonate (for TLS fingerprinting)
# -----------------------------------------
.PHONY: install-curl-impersonate clean-curl-impersonate download-curl-impersonate

CURL_IMP := $(BC)vendor/curl-impersonate/out/$(OS)-$(ARCH)
CURL_IMP_BUILD := $(BC)vendor/curl-impersonate/build
CURL_IMP_VERSION := $(shell cd $(BC)vendor/curl-impersonate && git describe --tags 2>/dev/null || git rev-parse --short HEAD)
CURL_IMP_RELEASE_URL := https://github.com/unstableneutron/browser/releases/download/curl-impersonate-$(CURL_IMP_VERSION)

## Download pre-built curl-impersonate from GitHub Releases (fast, recommended)
## Falls back to building from source if download fails
download-curl-impersonate:
	@if [ -f "$(CURL_IMP)/lib/libcurl-impersonate.a" ]; then \
		printf "\e[33mcurl-impersonate already installed at $(CURL_IMP)\e[0m\n"; \
	else \
		printf "\e[36mDownloading pre-built curl-impersonate $(CURL_IMP_VERSION) for $(OS)-$(ARCH)...\e[0m\n"; \
		mkdir -p $(CURL_IMP); \
		if curl -fL $(CURL_IMP_RELEASE_URL)/curl-impersonate-$(OS)-$(ARCH).tar.gz | tar -xzf - -C $(CURL_IMP); then \
			printf "\e[33mDone curl-impersonate $(OS)-$(ARCH)\e[0m\n"; \
		else \
			printf "\e[33mDownload failed, building from source...\e[0m\n"; \
			$(MAKE) install-curl-impersonate; \
		fi \
	fi

## Build curl-impersonate from source (requires cmake, ninja, go, autotools, zstd)
## Note: The upstream Makefile has issues with cd commands. We use gmake and proper env vars.
install-curl-impersonate: clean-curl-impersonate
	@printf "\e[36mBuilding curl-impersonate (this may take 5-10 minutes)...\e[0m\n"
	@mkdir -p $(CURL_IMP_BUILD)
ifeq ($(OS), macos)
	@cd $(CURL_IMP_BUILD) && \
		CPPFLAGS="-I/opt/homebrew/opt/zstd/include" \
		LDFLAGS="-L/opt/homebrew/opt/zstd/lib" \
		../configure --prefix=$(CURL_IMP) --enable-static
	@cd $(CURL_IMP_BUILD) && gmake build
else
	@cd $(CURL_IMP_BUILD) && \
		../configure --prefix=$(CURL_IMP) --enable-static
	@cd $(CURL_IMP_BUILD) && make build
endif
	@mkdir -p $(CURL_IMP)/lib $(CURL_IMP)/include
	@cp $(CURL_IMP_BUILD)/curl-*/lib/.libs/libcurl-impersonate.a $(CURL_IMP)/lib/ 2>/dev/null || \
		cp $(CURL_IMP_BUILD)/curl-*/src/.libs/libcurl-impersonate.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/boringssl-*/lib/libssl.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/boringssl-*/lib/libcrypto.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/nghttp2-*/installed/lib/libnghttp2.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/ngtcp2-*/installed/lib/libngtcp2.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/ngtcp2-*/installed/lib/libngtcp2_crypto_boringssl.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/nghttp3-*/installed/lib/libnghttp3.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/c-ares-*/installed/lib/libcares.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/brotli-*/out/installed/lib/libbrotlidec.a $(CURL_IMP)/lib/
	@cp $(CURL_IMP_BUILD)/brotli-*/out/installed/lib/libbrotlicommon.a $(CURL_IMP)/lib/
	@cp -r $(CURL_IMP_BUILD)/curl-*/include/curl $(CURL_IMP)/include/
	@cp -r $(CURL_IMP_BUILD)/boringssl-*/include/openssl $(CURL_IMP)/include/
	@printf "\e[33mDone curl-impersonate $(OS)-$(ARCH)\e[0m\n"

clean-curl-impersonate:
	@printf "\e[36mCleaning curl-impersonate build...\e[0m\n" && \
	rm -Rf $(CURL_IMP_BUILD) $(CURL_IMP)

# Docker
# ------
.PHONY: docker docker-impersonate docker-all

DOCKER_IMAGE := lightpanda/browser
DOCKER_TAG := local

## Build standard Docker image (no TLS fingerprinting)
docker:
	@printf "\e[36mBuilding Docker image (standard)...\e[0m\n"
	docker build --build-arg GIT_COMMIT=$$(git rev-parse --short HEAD 2>/dev/null || echo "unknown") \
		-t $(DOCKER_IMAGE):$(DOCKER_TAG) .

## Build Docker image with curl-impersonate (TLS fingerprinting enabled)
docker-impersonate:
	@printf "\e[36mBuilding Docker image with curl-impersonate (this may take 15-20 minutes)...\e[0m\n"
	docker build --build-arg USE_CURL_IMPERSONATE=1 \
		--build-arg GIT_COMMIT=$$(git rev-parse --short HEAD 2>/dev/null || echo "unknown") \
		-t $(DOCKER_IMAGE):$(DOCKER_TAG)-impersonate .

## Build both Docker images
docker-all: docker docker-impersonate
	@printf "\e[33mDone building all Docker images\e[0m\n"
